version: "3.7"

services:
  ########################
  # Setup client container
  ########################
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: yarn start
    stdin_open: true
